version: '3'
services:
  server:
    image: node:latest
    ports:
      - 5000:5000
    environment:
      - DB_NAME=todos
      - DB_CONNECTION=mongodb://max:notsosecret@db:27017
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    command: 'bash -c "npm install && npm run dev"'
  db:
    image: mongo:latest
    volumes:
      - 'mongodata:/var/lib/mongodb/data'
      - './db/setup.js:/docker-entrypoint-initdb.d/seeds.js:ro'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=max
      - MONGO_INITDB_DATABASE=todos
      - MONGO_INITDB_ROOT_PASSWORD=notsosecret
volumes:
  mongodata:
